todo/models.py
"""Database models for our application."""

from todo import db


class Category(db.Model):
    """Database table to store Todo tasks."""

    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    tasks = db.relationship("Task", backref="category", lazy="dynamic")
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))


class Task(db.Model):
    """Database table to store Todo tasks."""

    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.Text)
    done = db.Column(db.Boolean, default=False)
    category_id = db.Column(db.Integer, db.ForeignKey("category.id"))
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))

    def __repr__(self):
        """Better string representation of our task."""
        return f"<Task(id={self.id}, body={self.body})>"


class User(db.Model):
    """Database table to store User info (used by auth)."""

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.Text)
    password = db.Column(db.Text)

    def __repr__(self):
        """Representation of User by  username."""
        return f"<User(username={self.username})>"

todo/__init__.py
"""By creating this file, we turn "todo" directory into a Python package.

Usually the __init__.py file is empty.
One of the reasons why you might put some code here is convenience.
All the functions and variables from this file can be imported with just:
from todo import app, db
"""
import os

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

DB_USER = os.environ.get("DB_USER")
DB_P = os.environ.get("DB_P")


# Set up Flask and sqlite database
app = Flask(__name__)
app.secret_key = os.environ.get("KEY")
# Comment out mysql settings and uncomment the following line to use temp db
#app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///todo.db"
app.config[
    "SQLALCHEMY_DATABASE_URI"
] = f"mysql+pymysql://{DB_USER}:{DB_P}@localhost/todo"
#app.config[
#    "SQLALCHEMY_DATABASE_URI"
#] = f"mysql://bf72d761ba6b90:25e7a7b0@us-cdbr-east-04.cleardb.com/heroku_5b60fe94aba4833"
app.config["SESSION_TYPE"] = "filesystem"
# The following line is needed to suppress SQLALCHEMY_TRACK_MODIFICATIONS warning
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = True
db = SQLAlchemy(app)
migrate = Migrate(app, db)

# This import has to be AFTER the "app" and "db" setup!
# Otherwise you will run into circular imports issues
# Here is another idea how to deal with them:
# https://stackoverflow.com/a/42910185
from todo import views, auth  # noqa E402 isort:skip

app.register_blueprint(views.bp)
app.register_blueprint(auth.bp)

todo/auth.py
"""Views for auth module."""


import functools

from flask import (
    Blueprint,
    flash,
    g,
    redirect,
    render_template,
    request,
    session,
    url_for,
)

from werkzeug.security import check_password_hash

from todo.api import get_user, create_user

bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/register", methods=("GET", "POST"))
def register():
    """Validate user and call create_user function."""
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        error = None

        if not username:
            error = "Username is required."
        elif not password:
            error = "Password is required."
        elif get_user(username) is not None:
            error = "User {} is already registered.".format(username)

        if error is None:
            create_user(username, password)
            return redirect(url_for("auth.login"))

        flash(error)

    return render_template("auth/register.html")


@bp.route("/login", methods=("GET", "POST"))
def login():
    """Validate username, password, and create new session."""
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        error = None
        user = get_user(username=username)
        if user is None:
            error = "Incorrect username."
        elif not check_password_hash(user.password, password):
            error = "Incorrect password."

        if error is None:
            session.clear()
            session["user_id"] = user.id
            return redirect("/")

        flash(error)

    return render_template("auth/login.html")


@bp.before_app_request
def load_logged_in_user():
    """Load logged in user before each request."""
    user_id = session.get("user_id")

    if user_id is None:
        g.user = None
    else:
        g.user = get_user(user_id=user_id)


@bp.route("/logout")
def logout():
    """Clear session data."""
    session.clear()
    return redirect("/")


def login_required(view):
    """Use with views which are allowed only for logged in."""

    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for("auth.login"))

        return view(**kwargs)

    return wrapped_view

todo/views.py
"""URLs for our application."""

from flask import Blueprint, redirect, render_template, request
from todo.api import (
    get_tasks,
    get_categories,
    create_task,
    edit_task,
    delete_task,
    finish_task,
    unfinish_task,
    create_category,
    delete_category,
)

from todo.auth import login_required

bp = Blueprint("tasks", __name__, url_prefix="/")


@bp.route("/")
@login_required
def tasks_list():
    """Render the HTML at 'templates/application.html'."""
    tasks = get_tasks()
    categories = get_categories()
    # Render the HTML page located in "templates/application.html"
    # Passing tasks as a variable, so it can be used in the template
    return render_template("application.html", tasks=tasks, categories=categories)


@bp.route("/new_task")
@login_required
def task_form():
    """Render the HTML at 'templates/new_task.html'."""
    categories = get_categories()
    return render_template("new_task.html", categories=categories)


@bp.route("/new_category")
@login_required
def category_form():
    """Render the HTML at 'templates/new_category.html'."""
    return render_template("new_category.html")


@bp.route("/task", methods=["POST"])
@login_required
def task_create():
    """Get body & category from request and run 'api/create_task'."""
    body = request.form["body"]
    category = request.form["category"]
    create_task(body, category)
    # Redirect user to the main page, so the new task will be displayed
    return redirect("/")

@bp.route("/category")
@login_required
def category_list():
    """Render the HTML at 'templates/application.html'."""
    categories = get_categories()
    # Render the HTML page located in "templates/list_categories"
    return render_template("list_categories.html", categories=categories)



@bp.route("/category", methods=["POST"])
@login_required
def category_create():
    """Get body from request and run 'api/create_category'."""
    body = request.form["body"]
    create_category(body)
    categories = get_categories()
    # Redirect user to the main page, so the new task will be displayed
    return render_template("list_categories.html", categories=categories)


@bp.route("category/delete/<int:category_id>")
@login_required
def category_delete(category_id):
    """Run 'api/delete_category'."""
    delete_category(category_id)
    # Redirect user back to the main page, so the list of categorys will be updated
    return redirect("/category")


@bp.route("/edit", methods=["POST"])
@login_required
def task_edit():
    """Run api/edit_task."""
    result = request.get_json()
    body = result["body"]
    id = result["id"]
    edit_task(id, body)
    return redirect("/")


@bp.route("/delete/<int:task_id>")
@login_required
def task_delete(task_id):
    """Run 'api/delete_task'."""
    delete_task(task_id)
    # Redirect user back to the main page, so the list of tasks will be updated
    return redirect("/")


@bp.route("/done/<int:task_id>")
@login_required
def task_done(task_id):
    """Run 'api/finish_task'."""
    finish_task(task_id)
    return redirect("/")


@bp.route("/undo/<int:task_id>")
@login_required
def task_undone(task_id):
    """Run 'api/unfinish_task'."""
    unfinish_task(task_id)
    return redirect("/")

todo/templates/application.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TODO App</title>
    <!-- Add Bootstrap to our project (https://getbootstrap.com/) -->
    <link rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation.min.css"
    crossorigin="anonymous"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='style_1.css') }}" type="text/css"/>
    <script src="{{ url_for('static', filename='1.js') }}"></script>
  </head>
  <body>
      <nav>
	<ul class="medium-horizontal navbar">
          {% if g.user %}
             <li class="list-group-item fi-list"><span class="mb-2">{{ g.user['username'] }}</span>
             <li class="list-group-item"><a href="{{ url_for('auth.logout') }}">Log Out</a>
          {% else %}
             <li class="list-group-item"><a href="{{ url_for('auth.register') }}">Register</a>
             <li class="list-gorup-item"><a href="{{ url_for('auth.login') }}">Log In</a>
          {% endif %}
       </ul>
      </nav>
    <div class="container">
      <h1 class="text-center">My TODO List</h1>
      <div class="row justify-content-center">
	      <a type="submit" class="btn btn-warning mx-sm-3 mb-2"
		href='/new_task' role="button">Add task</a>
	      <a type="submit" class="btn btn-warning mx-sm-3 mb-2"
		href='/new_category' role="button">Add category</a>
	      <a type="submit" class="btn btn-warning mx-sm-3 mb-2"
		href='/category' role="button">List categories</a>

      </div>
      {% for category in categories %}
      <br>
      <div class="category">{{ category.body }} </div>
      <br>
      <ul class="list-group">
        {% for task in category.tasks %}
        <li class="list-group-item {% if task.done %}list-group-item-secondary{% endif %}">
          <div class="row justify-content-between">
            <div class="my-2 mx-sm-3">
		    <span role="listitem" id="taskbody_{{ task.id }}">
              {% if task.done %}<del>{% endif %}
              {{ task.body }}
              {% if task.done %}</del>{% endif %}
              </span>
            </div>
            <div class="my-2 mx-sm-3">
              {% if not task.done %}
	      <a class="btn btn-warning" role="button" onclick="return sendDataToEdit({{ task.id }})")>Edit</a>
	      <textarea style='display:none' placeholder='New text' name='body' id="input_{{ task.id }}"></textarea>
              <a class="btn btn-success" href="/done/{{ task.id }}" role="button">Done</a>
              {% endif%}
	      {% if task.done %}
	      <a class="btn btn-warning" href="/undo/{{ task.id }}" role="button">Undo</a>
	      {% endif%}
              <a class="btn btn-danger" href="/delete/{{ task.id }}" role="button">Delete</a>
            </div>
          </div>
        </li>
        {% endfor %}
      </ul>
      {% endfor %}
    </div>
  </body>
</html>

todo/templates/auth_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title%}{% endblock%}</title>
    <!-- Add Bootstrap to our project (https://getbootstrap.com/) -->
    <link rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation.min.css"
    crossorigin="anonymous"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='style_1.css') }}" type="text/css"/>
  </head>
  <body>
    <nav>
	<ul class="medium-horizontal navbar">
          {% if g.user %}
             <li class="list-group-item fi-list"><span>{{ g.user['username'] }}</span>
             <li class="list-group-item"><a href="{{ url_for('auth.logout') }}">Log Out</a>
          {% else %}
             <li class="list-group-item"><a href="{{ url_for('auth.register') }}">Register</a>
             <li class="list-group-item"><a href="{{ url_for('auth.login') }}">Log In</a>
          {% endif %}
       </ul>
    </nav>
    <section class="row justify-content-center">
	     <header>
             {% block header %}{% endblock %}
	    </header>
	    <div class="category">
               {% for message in get_flashed_messages() %}
               <div class="category">{{ message }}</div>
               {% endfor %}	    
           {% block content %}{% endblock %}
	    </div>

    </section>
 </body>
</html>

todo/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TODO App</title>
    <!-- Add Bootstrap to our project (https://getbootstrap.com/) -->
    <link rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation.min.css"
    crossorigin="anonymous"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='style_1.css') }}" type="text/css"/>
  </head>
  <body>
      <nav>
	<ul class="navbar static-top">
          {% if g.user %}
             <li class="list-group-item"><span class="mb-2">{{ g.user['username'] }}</span>
             <li class="list-group-item"><a href="{{ url_for('auth.logout') }}">Log Out</a>
          {% else %}
             <li class="list-group-item"><a href="{{ url_for('auth.register') }}">Register</a>
             <li class="list-group-item"><a href="{{ url_for('auth.login') }}">Log In</a>
          {% endif %}
       </ul>
      </nav>
    <div class="container">
	    {% block title %}
	    <h1 class="text-center">My TODO List</h1>
	    {% endblock %}
	    {% block content %}
      <div class="row justify-content-center">
	      <a type="submit" class="btn btn-warning mx-sm-3 mb-2"
		href='/new_task' role="button">Add task</a>
	      <a type="submit" class="btn btn-warning mx-sm-3 mb-2"
		href='/new_category' role="button">Add category</a>

      </div>
      {% for category in categories %}

      <br>
      <div class="category">{{ category.body }} </div>
      <br>
      <ul class="list-group">
        {% for task in category.tasks %}
        <li class="list-group-item {% if task.done %}list-group-item-secondary{% endif %}">
          <div class="row justify-content-between">
            <div class="my-2 mx-sm-3">
              <span role="listitem">
              {% if task.done %}<del>{% endif %}
              {{ task.body }}
              {% if task.done %}</del>{% endif %}
              </span>
            </div>
            <div class="my-2 mx-sm-3">
              {% if not task.done %}
              <a class="btn btn-success" href="/done/{{ task.id }}" role="button">Done</a>
              {% endif%}
	      {% if task.done %}
	      <a class="btn btn-warning" href="/undo/{{ task.id }}" role="button">Undo</a>
	      {% endif%}
              <a class="btn btn-danger" href="/delete/{{ task.id }}" role="button">Delete</a>
            </div>
          </div>
        </li>
        {% endfor %}
      </ul>
      {% endfor %}
      {% endblock %}
    </div>
  </body>
</html>

todo/templates/list_categories.html
{% extends 'base.html' %}
    {% block title %}<h1 class="text-center">Task Categories</h1>{% endblock %}
    <div class="container">
	    {% block content  %}
       <ul class="list-group">
        {% for category in categories %}
	<li class="list-group-item"> 
          <div class="row justify-content-between">
            <div class="my-2 mx-sm-3">
              <span role="listitem">
		      {{ category.body }}
              </span>
            </div>
      		<a type="submit" class="btn btn-danger" href="category/delete/{{ category.id }}" role="button">Delete category</a>
         </div>
        </li>
        {% endfor %}
      </ul>
    </div>
    <br></br>
       <div class="row justify-content-center"> 
	  <a class="btn btn-success" role="button" href="/">Back</a>
       </div>
       {% endblock  %}
       </div>   

todo/templates/new_category.html
{% extends "base.html" %}


{% block title  %}<h1 class="text-center">New category</h1>{% endblock %}
    <div class="container">
	    {% block content %}
      <div class="row justify-content-center">
        <form class="form-inline" action="/category" method="post">
          <div class="form-group">
	    <ul class="list-group">
              <li class="list-group-item">Category:
                <input type="text" placeholder="Body of the category" name="body"/>
	      </li>
	    </ul>  
          </div>
          <button type="submit" class="btn btn-success mx-sm-3 mb-2">Add category</button>
        </form>
   </div>
   <br></br>
     <div class="row justify-content-center"> 
	  <a class="btn btn-success" role="button" href="/">Back</a>
     </div>
     {% endblock %}
    </div>
  </body>
</html>

todo/templates/new_task.html
{% extends "base.html" %}


{% block title %} <h1 class="text-center">New task</h1>{% endblock  %}
    <div class="container">
	    {% block content %}
      <div class="row justify-content-center">
        <form class="form-inline" action="/task" method="post">
          <div class="form-group">
	    <ul class="list-group">
              <li class="list-group-item">Task:
                <input type="text" placeholder="Body of the task" name="body"/>
	      </li>
	      <li class="list-group-item">Category:
	    <select name="category">
		    {% for category in categories %}
		    <option value="{{ category.id }}">{{ category.body }}</option>
		    {% endfor %}
	    </select>
	       </li>
	     </ul>  
          </div>
          <button type="submit" class="btn btn-success mx-sm-3 mb-2">Add task</button>
        </form>
   </div>
   <br></br>
  <div class="row justify-content-center"> 
	  <a class="btn btn-success" role="button" href="/">Back</a>
	  {% endblock   %}
  </div>